codecov:
  bot: codecov-io
  notify:
    require_ci_to_pass: yes

coverage:
  range: 70...100
  round: down
  precision: 2

  status:
    project: yes
    patch: yes
    changes: no

comment: off

ignore:
  - "vendor/*"
  - "third_party/*"
  - "*.pb.go"
