env:
  - GO111MODULE=on
builds:
- main: cmd/serve/main.go
  binary: serve
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X main.version={{.Version}}
archives:
  - id: tarball
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macos
      386: i386
      amd64: x86_64
brews:
  -
    github:
      owner: syntaqx
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/syntaqx/serve
    description: serve is a static http server anywhere you need one.
    test: |
      system "#{bin}/serve version"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
