services:

  # Note: You probably will want to remove the `build: .` lines if you copy
  # these into your project. That is used to be able to rebuild the image
  # directly in the project repsitory.

  basic:
    build: .
    image: syntaqx/serve
    volumes:
      - ./static:/var/www
    ports:
      - 8080:8080

  basic_ssl:
    build: .
    image: syntaqx/serve
    volumes:
      - ./static:/var/www
      - ./fixtures:/etc/ssl
    ports:
      - 8888:8080
    command: serve -ssl -cert=/etc/ssl/cert.pem -key=/etc/ssl/key.pem -dir=/var/www
