#!/bin/bash

# Overrides the default "build" phase from Docker Hub
# https://docs.docker.com/docker-hub/builds/advanced/#custom-build-phase-hooks

docker build --build-arg VERSION="$DOCKER_TAG" \
    -f "$DOCKERFILE_PATH" \
    -t "$DOCKER_TAG" \
    .
