name: ci

on:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  # ensure tests work on a clean machine without building
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Go
      uses: actions/setup-go@v2
    -
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    -
      run: |
        go mod download
    -
      run: |
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    -
      uses: codecov/codecov-action@v2
      with:
        # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.txt
        flags: unittests # optional
        # name: codecov-umbrella # optional
        # fail_ci_if_error: true # optional (default = false)
        # verbose: true # optional (default = false)
